### ISSUE TITLE
Error: prefix must not start with a /. This is a bug.

### ISSUE THREAD

**Issue by dustinlacewell** [cmfcmf/docusaurus-search-local#136]
### Please describe the bug you are seeing

When building my site I get the following:

```
[Local Search] [INFO]: Gathering documents
[ERROR] Unable to build website for locale en.
[ERROR] Error: prefix must not start with a /. This is a bug.
    at urlMatchesPrefix (/Users/dustinlacewell/src/volley-docs/node_modules/@cmfcmf/docusaurus-search-local/lib/server/index.js:17:15)
    at /Users/dustinlacewell/src/volley-docs/node_modules/@cmfcmf/docusaurus-search-local/lib/server/index.js:224:29
    at Array.flatMap (<anonymous>)
    at Object.postBuild (/Users/dustinlacewell/src/volley-docs/node_modules/@cmfcmf/docusaurus-search-local/lib/server/index.js:210:18)
    at /Users/dustinlacewell/src/volley-docs/node_modules/@docusaurus/core/lib/commands/build.js:171:22
    at Array.map (<anonymous>)
    at buildLocale (/Users/dustinlacewell/src/volley-docs/node_modules/@docusaurus/core/lib/commands/build.js:167:31)
    at async tryToBuildLocale (/Users/dustinlacewell/src/volley-docs/node_modules/@docusaurus/core/lib/commands/build.js:38:20)
    at async mapAsyncSequential (/Users/dustinlacewell/src/volley-docs/node_modules/@docusaurus/utils/lib/jsUtils.js:34:24)
    at async Command.build (/Users/dustinlacewell/src/volley-docs/node_modules/@docusaurus/core/lib/commands/build.js:73:21)
[INFO] Docusaurus version: 2.0.1
Node version: v18.4.0
```

### Which version of Docusaurus and @cmfcmf/docusaurus-search-local are you using?

```
npm list '@docusaurus/core' '@cmfcmf/docusaurus-search-local'                                                                                                                                                                    ~/src/volley-docs
dustin-solid-docs@0.0.0 /Users/dustinlacewell/src/volley-docs
├─┬ @cmfcmf/docusaurus-search-local@0.11.0
│ └── @docusaurus/core@2.0.1 deduped
├── @docusaurus/core@2.0.1
├─┬ @docusaurus/plugin-content-docs@2.0.1
│ └── @docusaurus/core@2.0.1 deduped
├─┬ @docusaurus/preset-classic@2.0.1
│ ├── @docusaurus/core@2.0.1 deduped
│ ├─┬ @docusaurus/plugin-content-blog@2.0.1
│ │ └── @docusaurus/core@2.0.1 deduped
│ ├─┬ @docusaurus/plugin-content-pages@2.0.1
│ │ └── @docusaurus/core@2.0.1 deduped
│ ├─┬ @docusaurus/plugin-debug@2.0.1
│ │ └── @docusaurus/core@2.0.1 deduped
│ ├─┬ @docusaurus/plugin-google-analytics@2.0.1
│ │ └── @docusaurus/core@2.0.1 deduped
│ ├─┬ @docusaurus/plugin-google-gtag@2.0.1
│ │ └── @docusaurus/core@2.0.1 deduped
│ ├─┬ @docusaurus/plugin-sitemap@2.0.1
│ │ └── @docusaurus/core@2.0.1 deduped
│ ├─┬ @docusaurus/theme-classic@2.0.1
│ │ └── @docusaurus/core@2.0.1 deduped
│ └─┬ @docusaurus/theme-search-algolia@2.0.1
│   └── @docusaurus/core@2.0.1 deduped
└─┬ docusaurus-plugin-sass@0.2.2
  └── @docusaurus/core@2.0.1 deduped
```

### Which Node.js version are you using?

v18.4.0

### Which theme are you using?

Yes, I am using @docusaurus/theme-classic

### How does your plugin config look like?

```
        [require.resolve("@cmfcmf/docusaurus-search-local"),
        {
            indexPages: true,
        }],
```

**Comment by AdamWillford** [comment]
Did you end up finding a fix/workaround for this as of yet?

**Comment by aleksimo** [comment]
Caught the same bug. I suppose, it's somehow connected with the [Multidoc](https://docusaurus.io/docs/docs-multi-instance) feature. When I add the plugin to a newly installed instance, everything works fine. But, once I place articles in the root folder next to **/docs** (and make some versioned), the build fails with this very error.
