### ISSUE TITLE
An error occurred while using the zh language

### ISSUE THREAD

**Issue by ssangyongsports** [cmfcmf/docusaurus-search-local#155]
### Please describe the bug you are seeing

An error occurred while using the zh language

### How can we best reproduce the bug?

ERROR] Error: Cannot find module '@node-rs/jieba'
--
23:22:45.161 | Require stack:
23:22:45.161 | - /vercel/path0/node_modules/lunr-languages/lunr.zh.js
23:22:45.161 | - /vercel/path0/node_modules/@cmfcmf/docusaurus-search-local/lib/server/index.js
23:22:45.161 | - /vercel/path0/node_modules/@docusaurus/core/lib/server/plugins/configs.js
23:22:45.162 | - /vercel/path0/node_modules/@docusaurus/core/lib/server/plugins/init.js
23:22:45.162 | - /vercel/path0/node_modules/@docusaurus/core/lib/server/plugins/index.js
23:22:45.162 | - /vercel/path0/node_modules/@docusaurus/core/lib/server/index.js
23:22:45.162 | - /vercel/path0/node_modules/@docusaurus/core/lib/commands/build.js
23:22:45.162 | - /vercel/path0/node_modules/@docusaurus/core/lib/index.js
23:22:45.162 | at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
23:22:45.162 | at Module._load (node:internal/modules/cjs/loader:841:27)
23:22:45.162 | at Module.require (node:internal/modules/cjs/loader:1061:19)
23:22:45.162 | at require (node:internal/modules/cjs/helpers:103:18)
23:22:45.162 | at /vercel/path0/node_modules/lunr-languages/lunr.zh.js:33:30
23:22:45.163 | at Object.<anonymous> (/vercel/path0/node_modules/lunr-languages/lunr.zh.js:38:2)
23:22:45.163 | at Module._compile (node:internal/modules/cjs/loader:1159:14)
23:22:45.163 | at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
23:22:45.163 | at Module.load (node:internal/modules/cjs/loader:1037:32)
23:22:45.163 | at Module._load (node:internal/modules/cjs/loader:878:12)
23:22:45.163 | [INFO] Docusaurus version: 2.1.0
23:22:45.163 | Node version: v18.12.1
23:22:45.215 | Error: Command "npm run build" exited with 1

### Which version of Docusaurus and @cmfcmf/docusaurus-search-local are you using?

0.11.0

### Which Node.js version are you using?

16.14

### Which theme are you using?

Yes, I am using @docusaurus/theme-classic

### How does your plugin config look like?

https://github.com/ssangyongsports/github-uiwszudff/blob/main/docusaurus.config.js

**Comment by ssangyongsports** [comment]
Sorry,I forget to install node-rs/jieba'
