### ISSUE TITLE
Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by xescuder** [cmfcmf/docusaurus-search-local#5]
At npm run build / yarn build, the next error appears at the end of the process (after Client and Server have compiled successfully):

TypeError: Cannot read property 'type' of undefined
    at getText (/Users/escuderx/Projects/ster-website/node_modules/@cmfcmf/docusaurus-search-local/src/parse.js:54:17)
    at module.exports.html2text (/Users/escuderx/Projects/ster-website/node_modules/@cmfcmf/docusaurus-search-local/src/parse.js:123:20)
    at Promise.all.data.map (/Users/escuderx/Projects/ster-website/node_modules/@cmfcmf/docusaurus-search-local/src/index.js:122:45)

**Comment by cmfcmf** [comment]
Hi @xescuder, thank you for your report. I just published version 0.1.1 which might fix this problem. Can you please upgrade to 0.1.1 and check if it works now? If not, please build your documentation with `DEBUG=1 yarn build` / `DEBUG=1 npm run build` to see which file produces the error. Would it be possible for you to share this file? 

Could you also provide the following information?

- Which version of Docusaurus are you using?
- Are you using a custom theme?
- Paste the plugin config of the local search plugin from your `docusaurus.config.js` file

**Comment by cmfcmf** [comment]
I'm assuming that this is now fixed. Please re-open or create a new issue if the issue persists.
