### ISSUE TITLE
TypeError: Cannot read property 'tokenizerSeparator' of undefined

### ISSUE THREAD

**Issue by apidev234** [cmfcmf/docusaurus-search-local#75]
TypeError: Cannot read property 'tokenizerSeparator' of undefined
    at cmfcmfDocusaurusSearchLocal (/Users/gaurish/Desktop/Coding/Report-API-Docs/node_modules/@cmfcmf/docusaurus-search-local/lib/server/index.js:42:189)
    at /Users/gaurish/Desktop/Coding/Report-API-Docs/node_modules/@docusaurus/core/lib/server/plugins/init.js:34:54
    at Array.map (<anonymous>)
    at Object.initPlugins (/Users/gaurish/Desktop/Coding/Report-API-Docs/node_modules/@docusaurus/core/lib/server/plugins/init.js:15:10)
    at Object.loadPlugins (/Users/gaurish/Desktop/Coding/Report-API-Docs/node_modules/@docusaurus/core/lib/server/plugins/index.js:41:28)
    at Object.load (/Users/gaurish/Desktop/Coding/Report-API-Docs/node_modules/@docusaurus/core/lib/server/index.js:57:62)
    at start (/Users/gaurish/Desktop/Coding/Report-API-Docs/node_modules/@docusaurus/core/lib/commands/start.js:45:34)
    at /Users/gaurish/Desktop/Coding/Report-API-Docs/node_modules/@docusaurus/core/bin/docusaurus.js:29:5
    at Command.<anonymous> (/Users/gaurish/Desktop/Coding/Report-API-Docs/node_modules/@docusaurus/core/bin/docusaurus.js:93:23)
    at Command.listener (/Users/gaurish/Desktop/Coding/Report-API-Docs/node_modules/@docusaurus/core/node_modules/commander/index.js:370:29)
    at Command.emit (node:events:394:28)
    at Command.parseArgs (/Users/gaurish/Desktop/Coding/Report-API-Docs/node_modules/@docusaurus/core/node_modules/commander/index.js:892:12)
    at Command.parse (/Users/gaurish/Desktop/Coding/Report-API-Docs/node_modules/@docusaurus/core/node_modules/commander/index.js:642:21)
    at Object.<anonymous> (/Users/gaurish/Desktop/Coding/Report-API-Docs/node_modules/@docusaurus/core/bin/docusaurus.js:116:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Getting this issue while running macOs, v2 of docusaurus

**Comment by cmfcmf** [comment]
Please provide more information, including your `docusaurus.config.js` file.
